#!/bin/bash

(

  create_real_file() {
    file=$1
    cp -fi $HOME/dotfiles/$file.sample $HOME/$file
  }

  symlink() {
    file=$1
    unlink $HOME/$file
    echo -e "Making symlink: ~/dotfiles/${file} -> ~/${file}"
    ln -s $HOME/dotfiles/$file $HOME/$file
  }

  symlink ".bash"
  symlink ".bash_profile"
  symlink ".bashrc"
  symlink ".tmux"
  symlink ".tmux.conf"
  symlink ".vim"
  symlink ".vim/.backups"

  create_real_file ".bashrc"
  create_real_file ".bash_profile"
  create_real_file ".tmux/theme.sh"

)
